name: Deploy Package

on:
  push:
    tags:
      - "v**"

jobs:
  spelling:
    name: Check Spellings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check Spelling
        uses: streetsidesoftware/cspell-action@v1.3.4

  test:
    name: Test before Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: npm run start
      - name: Test Package
        run: npm test
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: dist

  publish-gpr:
    name: Publish to Github Package Registry
    needs: [test, spelling]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: "npm"
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: npm install
      - name: Build Package
        run: npm run start
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-ghr:
    name: Upload files to ${{ github.ref }}
    needs: [test, spelling]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          name: distribution
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          files: |
            ${{ steps.download.outputs.download-path }}/colors.min.css
            ${{ steps.download.outputs.download-path }}/colors.less
            ${{ steps.download.outputs.download-path }}/colors.scss
            ${{ steps.download.outputs.download-path }}/colors.json
            ${{ steps.download.outputs.download-path }}/colors.ts
            ${{ steps.download.outputs.download-path }}/colors.js
            ${{ steps.download.outputs.download-path }}/colors.d.ts
          draft: false
          prerelease: false
