name: Build & Test

on:
  push:
    tags-ignore:
      - "v**"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  spelling:
    name: Check Spellings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check Spelling
        uses: streetsidesoftware/cspell-action@v1.3.5

  build:
    name: Build Package and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: npm run start
      - name: Test Package
        if: ${{ always() }}
        run: npm test

  npm_lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Lint Package
        run: npm run lint

  super_lint:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Super Linter
        uses: docker://github/super-linter:v2.2.0
        env:
          DEFAULT_BRANCH: main
          VALIDATE_JSON: false
          VALIDATE_MD: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_TYPESCRIPT_STANDARD: false
